version: '3'
services:
  notary:
    volumes:
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/node.conf:/etc/corda/node.conf
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/indy.properties:/etc/corda/indy.properties
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/pool_transactions_genesis:/etc/corda/pool_transactions_genesis
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/certificates:/opt/corda/certificates
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/logs:/opt/corda/logs
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/persistence:/opt/corda/persistence
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/persistence.mv.db:/opt/corda/persistence.mv.db
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/cordapps:/opt/corda/cordapps
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/network-parameters:/opt/corda/network-parameters
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/additional-node-infos:/opt/corda/additional-node-infos
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\Notary/drivers:/opt/corda/drivers
    environment:
      - ACCEPT_LICENSE=${ACCEPT_LICENSE}
    ports:
      - 10003
      - 22022
    image: corda/corda-zulu-java1.8-4.6:latest
    entrypoint: java -jar /opt/corda/bin/corda.jar --allow-hibernate-to-manage-app-schema --base-directory /opt/corda/ --config-file /etc/corda/node.conf
  partya:
    volumes:
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/node.conf:/etc/corda/node.conf
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/indy.properties:/etc/corda/indy.properties
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/pool_transactions_genesis:/etc/corda/pool_transactions_genesis
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/certificates:/opt/corda/certificates
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/logs:/opt/corda/logs
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/persistence:/opt/corda/persistence
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/persistence.mv.db:/opt/corda/persistence.mv.db
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/cordapps:/opt/corda/cordapps
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/network-parameters:/opt/corda/network-parameters
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/additional-node-infos:/opt/corda/additional-node-infos
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyA/drivers:/opt/corda/drivers
    environment:
      - ACCEPT_LICENSE=${ACCEPT_LICENSE}
    ports:
      - 10006
      - 22022
    image: corda/corda-zulu-java1.8-4.6:latest
    entrypoint: java -jar /opt/corda/bin/corda.jar --allow-hibernate-to-manage-app-schema --base-directory /opt/corda/ --config-file /etc/corda/node.conf
  partyb:
    volumes:
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/node.conf:/etc/corda/node.conf
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/indy.properties:/etc/corda/indy.properties
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/pool_transactions_genesis:/etc/corda/pool_transactions_genesis
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/certificates:/opt/corda/certificates
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/logs:/opt/corda/logs
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/persistence:/opt/corda/persistence
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/persistence.mv.db:/opt/corda/persistence.mv.db
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/cordapps:/opt/corda/cordapps
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/network-parameters:/opt/corda/network-parameters
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/additional-node-infos:/opt/corda/additional-node-infos
      - C:\Users\stefa\Workspace\repositories\samples-kotlin\Basic\ping-pong\build\nodes\PartyB/drivers:/opt/corda/drivers
    environment:
      - ACCEPT_LICENSE=${ACCEPT_LICENSE}
    ports:
      - 10009
      - 22022
    image: corda/corda-zulu-java1.8-4.6:latest
    entrypoint: java -jar /opt/corda/bin/corda.jar --allow-hibernate-to-manage-app-schema --base-directory /opt/corda/ --config-file /etc/corda/node.conf
